--CREATE TABLE patient(patid number(2),age number(2),fname varchar2(5),lname varchar2(5),gender varchar2(1));
--INSERT INTO patient(patid,age,fname,lname,gender) VALUES(13,20,'luka','mary','f');
--INSERT INTO patient(patid,age,fname,lname,gender) VALUES(14,65,'sathya','githray','m');
--INSERT INTO patient(patid,age,fname,lname,gender) VALUES(15,65,'adiya','varma','m');
--INSERT INTO patient(patid,age,fname,lname,gender) VALUES(15,65,'adiya','reddy','m');
--SELECT * from patient; 
--select patid,fname,lname from patient;
--SELECT patid as patientid,fname as firstname,lname as lastname from patient;
--select fname from patient WHERE gender='m';
select lname FROM patient WHERE gender not like 'm';
SELECT lname FROM patient where gender!='f';
SELECT count (lname) FROM patient where gender='m';

--CREATE TABLE patient(patid number(2),age number(2),fname varchar2(5),lname varchar2(5),gender varchar2(1));
--INSERT INTO patient(patid,age,fname,lname,gender) VALUES(13,20,'luka','mary','f');
--INSERT INTO patient(patid,age,fname,lname,gender) VALUES(14,65,'sathya','githray','m');
--INSERT INTO patient(patid,age,fname,lname,gender) VALUES(15,65,'adiya','varma','m');
--INSERT INTO patient(patid,age,fname,lname,gender) VALUES(16,65,'adiya','reddy','m');
--SELECT * from patient; 
--select patid,fname,lname from patient;
--SELECT patid as patientid,fname as firstname,lname as lastname from patient;
--select fname from patient WHERE gender='m';
--select lname FROM patient WHERE gender not like 'm';
--SELECT lname FROM patient where gender!='f'; 
--SELECT count (lname) FROM patient where gender='m';
--CREATE TABLE docu(name varchar2(5),phno number(10),dutytime varchar2(3) CHECK(dutytime in('mor','eve','ngt')));
--INSERT INTO docu(name,phno,dutytime) VALUES('mary',9123456789,'mor');
--INSERT INTO docu(name,phno,dutytime) VALUES('grace',9123456123,'mor');
--INSERT INTO docu(name,phno,dutytime) VALUES('latha',9123456456,'eve');
--INSERT INTO docu(name,phno,dutytime) VALUES('sandy',9123456678,'eve');
--INSERT INTO docu(name,phno,dutytime) VALUES('nivi',9123456098,'ngt');
--select * from docu;
--CREATE TABLE consulation(consid number(2),fees number(3),healthissue varchar2(10),consult_date date);
--INSERT INTO  consulation(consid,fees,healthissue,consult_date) VALUES(13,500,'headache',date());
--INSERT INTO  consulation(consid,fees,healthissue,consult_date) VALUES(14,500,'cancer',date());
--INSERT INTO  consulation(consid,fees,healthissue,consult_date) VALUES(15,500,'sinus',date());
--INSERT INTO  consulation(consid,fees,healthissue,consult_date) VALUES(16,500,'vising',date());
select * from consulation;
--SELECT p1.patid,fname,gender,consult_date FROM patient as p1 JOIN consulation as c1 on p1.patid=c1.consid;
                                                                     
